version: 2.1

jobs:
  publish:
    docker:
      - image: node:18
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Set Git User
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "CircleCI Bot"

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Increment Version (Patch)
          command: |
            npm version patch -m "ci: bump version to %s [skip ci]"
            git push --follow-tags https://${GH_TOKEN}@github.com/vspok/baileys-bottle-devstroupe.git

      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc

      - run:
          name: Publish to NPM
          command: npm publish --access public

      - run:
          name: Clean up
          command: rm ~/.npmrc

workflows:
  version: 2
  publish_on_master:
    jobs:
      - publish:
          filters:
            branches:
              only: master
